### ISSUE TITLE
Deploy to CICS does not need the project cloned to zFS

### ISSUE THREAD

**Issue by ChrisAtkinson1** [cicsdev/cics-nodejs-invoke#1]
I found I did not need to git clone this to zFS at all.

These steps in the documentation - I believe should be changed.

Deploying the Node.js application in CICS

    Clone this repository to a directory on zFS.

    git clone https://github.com/cicsdev/cics-nodejs-invoke.git

    Download the Node.js modules that the application depends on:

    cd cics-nodejs-invoke/projects/cics-nodejs-invoke
    npm install

To Deploying the Node.js application in CICS.

From the local directory cd into the \cics-nodejs-invoke\projects\cics-nodejs-invoke

This directory represents the CICS bundle.  You use these artifacts to create the CICS bundle.

You can then follow steps 3 onwards and it should work.  Removes the need to configure git on zFS too.

**Comment by markcocker** [comment]
@ChrisAtkinson1 Above changes now merged.
