### ISSUE TITLE
Install on z/OS without Internet conenction

### ISSUE THREAD

**Issue by namnetes** [cicsdev/cics-nodejs-invoke#7]
Hello,

How can I install the package and satisfy all necessary dependencies on z/OS system without any Internet connection ?

Thank's for your help.
Best regards
Alan

**Comment by markcocker** [comment]
@namnetes Typically companies setup an internal enterprise registry with approved packages and setup npm to access that instead, eg. see [Configuring your registry settings as an npm Enterprise user](https://docs.npmjs.com/configuring-your-registry-settings-as-an-npm-enterprise-user). Another approach if your dependencies do not include natives is to download those on another platform and copy them onto z/OS, either into a global path or a parent path of the application.

**Comment by namnetes** [comment]
@markcocker Thank you for your reply.
I will follow the suggested other approach to sasisfy the depencies.
