### ISSUE TITLE
words matter scan

### ISSUE THREAD

**Issue by PhilWakelin** [cicsdev/cics-nodejs-invoke#9]
The following files in this repo contain the word "master"

cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\css\bootstrap.css line: 3 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 3 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 13 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 62 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 151 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 259 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 465 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 636 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 784 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 1029 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 1428 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 1539 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 1693 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.js line: 1819 contains: master
cics-nodejs-invoke\projects\cics-nodejs-invoke\public\assets\js\bootstrap.min.js line: 3 contains: master

@markcocker can you review and update It looks like most of these just need updating to the new main repo branch

**Comment by markcocker** [comment]
The Bootstrap version 5.0.0-alpha2  addressed this in https://github.com/twbs/bootstrap/pull/31066 on 19 Jun 2020. According to https://getbootstrap.com/docs/versions/ the only version of Boostrap for download that includes this pull request is still in beta (version 5 beta 3).

I suggest waiting until the next non-beta version is available before including it in this repo.

**Comment by PhilWakelin** [comment]
>  
> The Bootstrap version 5.0.0-alpha2 addressed this in [twbs/bootstrap#31066](https://github.com/twbs/bootstrap/pull/31066) on 19 Jun 2020. According to https://getbootstrap.com/docs/versions/ the only version of Boostrap for download that includes this pull request is still in beta (version 5 beta 3).
> 
> I suggest waiting until the next non-beta version is available before including it in this repo.

The boostrap issue is re. whitelist and blacklist terms. However, the hits in this repo concern the term `master` in the license location comments i.e.
``` * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)```
All of which have already been renamed to `main` in the latest version of bootstrap 4.6

**Comment by markcocker** [comment]
Renamed `master` branch to `main`.
